"""Initial migration.

Revision ID: bb40ca493eda
Revises: 
Create Date: 2024-12-11 12:33:21.735027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb40ca493eda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celebrant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('shareable_link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shareable_link')
    )
    op.create_table('wish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celebrant_id', sa.Integer(), nullable=False),
    sa.Column('well_wisher_name', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['celebrant_id'], ['celebrant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wish')
    op.drop_table('celebrant')
    # ### end Alembic commands ###
